apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: spinnaker
spec:
  containers:
  - name: nginx
    image: fkklx/lx-test
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
